version: '3'
services:
    web:
        build: .
        container_name: web
        ports:
            - 3004:3000
        networks: 
            - nodeapp
        environment:
            - PORT=3000
            - EV_HOST=0.0.0.0
            - DB_HOST=mongodb://mongo/jwt-auth:27017
            - DB_PORT=27017
            - DB_NAME=jwt-auth
            - ENV=production
            - JWT_SECRET=RGV1cyBlc3TDoSBubyBjb21hbmRv
        volumes:
            - './src:/app/src'
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/mongodb
        ports:
            - '27017:27017'
        networks:
            - nodeapp
networks:
    nodeapp:
        driver: bridge
